### Request to Root Endpoint ###
GET / HTTP/1.1
Host: localhost:4221
User-Agent: SampleClient/1.0
Accept: */*

---

### Request to Echo Endpoint ###
GET /echo/HelloWorld HTTP/1.1
Host: localhost:4221
User-Agent: SampleClient/1.0
Accept: text/plain

---

### Request to User-Agent Endpoint ###
GET /user-agent HTTP/1.1
Host: localhost:4221
User-Agent: SampleClient/1.0
Accept: text/plain

---

### Request to Files Endpoint (Existing File) ###
GET /files/foo HTTP/1.1
Host: localhost:4221
User-Agent: SampleClient/1.0
Accept: */*

---

### Request to Files Endpoint (Non-existing File) ###
GET /files/non_existent_file HTTP/1.1
Host: localhost:4221
User-Agent: SampleClient/1.0
Accept: */*